---
abstract: 'a module that does something-or-other'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlX-Window
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  PerlX::Window:
    file: lib/PerlX/Window.pm
    version: 0.001
recommends:
  Hash::FieldHash: 0
  Variable::Magic: 0
requires:
  Data::Alias: 0
  Exporter::Shiny: 0
  perl: 5.008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/PerlX-Window/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=PerlX-Window
  homepage: https://metacpan.org/release/PerlX-Window
  license: http://dev.perl.org/licenses/
version: 0.001
